### PR TITLE
Add figsize and dpi arguments to plotting functions

### PR DESCRIPTION
**Pull request by gmgall**
The functions

- `plot_probability_distribution`
- `plot_success_probability`
- `plot_function`

now have `figsize` and `dpi` arguments.

I believe there is still refactoring to be done, no need to merge immediately. I'm opening this PR to allow for others to test this changes.

### CODE REVIEW

**Comment by gustavowl** [comment]
Before testing the changes, I have a suggestion. And I'd like you opinion on it.

The `_configure_.*_figure` functions (the ones pointed by the `configs` dict) assign default values to `fig_width`, `fig_height` and `dpi`. Since these are internal functions, I think we should remove the default values.

Consequently, in these functions, I think we should remove the assignments that use `plt.rcParams["figure.figsize"]`.

**Comment by gmgall** [comment]
I removed the default values in commit 33d0f8a2b07384d4fcf7638cd00d9b224138cc69.

The `hiperwalk` package is at a non importable state at the moment (4b6c8749ccd1ca08ce86899977d030dd6ab486c4). I will continue refactoring when it is possible to import the package for testing at least a few figures.

I believe there isn't a lot to be done for this feature. Maybe eliminate a couple of redundancies and deleting the references to `plt.rcParams["figure.figsize"]`.

**Comment by gustavowl** [comment]
I agree. Delete the references to `plt.rcParams["figure.figsize"]` and let me know.

Once `hiperwalk` is in an importable state, I will let you know.

**Comment by gmgall** [comment]
Since this PR is a couple of weeks old, I made a local merge between `master` and `feature_figsize` to test the mergeability of these changes.

The example provided for inclusion on the website works fine.

```python
import hiperwalk as hpw
import numpy as np

N = 128
# adjacency matrix of complete graph with self loops
A = np.ones((N, N))
graph = hpw.Graph(A)
qw = hpw.Coined(graph, shift='flipflop', coin='G', marked={'-G': [0]})
t_final = (round(4*np.pi*np.sqrt(N)/4),1)
states = qw.simulate(time=t_final,
                     state=qw.uniform_state())
marked_prob = qw.success_probability(states)
hpw.plot_success_probability(t_final, marked_prob, figsize=(6,6), dpi=100)
```

The generated image is the following:

ex_figsize

---

The code example from the [tutorial](https://hiperwalk.org/docs/stable/tutorial/index.html)...

```python
import hiperwalk as hpw
N = 11
line = hpw.Line(N)
qw = hpw.Coined(line)
vertex = N // 2
initial_state = qw.ket(vertex, vertex + 1)
final_state = qw.simulate(time=(N//2, 1), initial_state=initial_state)
probability = qw.probability_distribution(final_state)
hpw.plot_probability_distribution(probability, filename='hello', show=True)
hpw.plot_probability_distribution(probability, filename='hello2.gif', plot='bar', animate=True, show=True, figsize=(6,5))
```

fails way before the plotting process on `hiperwalk/graph/line.py`:

```
Traceback (most recent call last):
  File "/home/guilherme/hdd/hiperwalk/hello_world.py", line 3, in <module>
    line = hpw.Line(N)
  File "/home/guilherme/hdd/hiperwalk/hiperwalk/graph/line.py", line 40, in Line
    g = SquareLattice(num_vert, basis, False, weights, multiedges)
NameError: name 'weights' is not defined
```

`examples/continuous-cycle.py` and `examples/coined-hypercube.py` fail before plotting as well.

**Comment by gustavowl** [comment]
Commit [e3f77eb](https://github.com/hiperwalk/hiperwalk/commit/e3f77eb5d6ec64956a35aa3d416f3b259ae65ad8) fixes the error that raises the `NameError: name 'weights' is not defined` exception.

The example from the tutorial will be updated in the future. Only the `qw.ket` line needs to be changed.

```python
import hiperwalk as hpw
N = 11
line = hpw.Line(N)
qw = hpw.Coined(line)
vertex = N // 2
# Parenthesis were added to denote arc notation
initial_state = qw.ket((vertex, vertex + 1))
final_state = qw.simulate(time=(N//2, 1), initial_state=initial_state)
probability = qw.probability_distribution(final_state)
hpw.plot_probability_distribution(probability, filename='hello', show=True)
hpw.plot_probability_distribution(probability, filename='hello2.gif', plot='bar', animate=True, show=True, figsize=(6,5))
```

With this change, the code runs fine.

**Pull request merged**
